name: Build and Release
run-name: ${{ gitea.actor }} has triggered Build and Release 🚀
on: [push]

jobs:
  Explore-Gitea-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ gitea.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by Gitea!"
      - run: echo "🔎 The name of your branch is ${{ gitea.ref }} and your repository is ${{ gitea.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "💡 The ${{ gitea.repository }} repository has been cloned to the runner."
      - name: 🖥️ The workflow is now ready to test your code on the runner.
        run: |
          ls ${{ gitea.workspace }}
      - name: 👉 📦 Installing Node
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"
      - name: 👉 📦 Installing Dependencies
        run: |
          npm ci
      - name: 🔧 Build application
        run: |
          npm run build
      - name: 🔧 Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
        config-inline: |
          [registry."registry:5000"]
            http = true
            insecure = true
      - name: 🔧 Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: registry:5000/sam/personal-website:latest
          registry: registry:5000